# **Players**

This dataset contains information about baseball players, including personal details, physical attributes, and career timelines. 

### **Table: players**

- **`id`:** unique identifier for each player  
- **`first_name`:** player's first name  
- **`last_name`:** player's last name  
- **`birth_city`:** city of birth  
- **`birth_state`:** state of birth  
- **`birth_country`:** country of birth  
- **`bats`:** batting hand (L = left, R = right)  
- **`throws`:** throwing hand (L = left, R = right)  
- **`height`:** height of the player  
- **`weight`:** weight of the player  
- **`debut`:** date of first professional game  
- **`final_game`:** date of last professional game

In [1]:
import pandas as pd 
import sqlite3
conn = sqlite3.connect("players.db")

### **BASIC FILTERS**

Place of birth of Jackie Robinson

In [9]:
query = """ 

SELECT birth_city, birth_state, birth_country
FROM players
WHERE first_name = 'Jackie'
AND last_name = 'Robinson';

"""
pd.read_sql(query,conn)

  birth_city birth_state birth_country
0      Cairo          GA           USA

Batting hand of Babe Ruth

In [10]:
query = """ 

SELECT bats
FROM players
WHERE first_name = 'Babe'
AND last_name = 'Ruth';

"""

pd.read_sql(query,conn)

  bats
0    L

Players without debut date (missing data)

In [11]:
query = """ 

SELECT id
FROM players
WHERE debut IS NULL;

"""
pd.read_sql(query,conn)

        id
0    20557
1    20558
2    20559
3    20560
4    20561
..     ...
208  20765
209  20766
210  20767
211  20768
212  20769

[213 rows x 1 columns]

### **FILTERING + SORTING**

Players born outside the USA

In [6]:
query = """ 

SELECT first_name, last_name
FROM players
WHERE birth_country != 'USA'
ORDER BY first_name ASC, last_name ASC;

"""
pd.read_sql(query,conn)

     first_name   last_name
0         A. J.     Jimenez
1         Aaron     Altherr
2         Aaron       Guiel
3         Aaron      Myette
4         Aaron  Whitefield
...         ...         ...
2809   Yusmeiro       Petit
2810    Yusniel        Diaz
2811       Zach         Pop
2812      Zoilo     Almonte
2813      Zoilo   Versalles

[2814 rows x 2 columns]

Players who bat right-handed

In [7]:
query = """ 

SELECT first_name, last_name
FROM players
WHERE bats = 'R'
ORDER BY first_name ASC, last_name ASC;

"""
pd.read_sql(query,conn)

      first_name  last_name
0          A. J.     Achter
1          A. J.      Alexy
2          A. J.    Burnett
3          A. J.       Cole
4          A. J.      Ellis
...          ...        ...
12873     Zelous    Wheeler
12874      Ziggy   Hasbrook
12875       Zinn       Beck
12876        Zip      Zabel
12877      Zoilo  Versalles

[12878 rows x 2 columns]

Players born in Pittsburgh, PA ordered by debut

In [8]:
query = """ 

SELECT first_name, last_name, debut
FROM players
WHERE birth_city = 'Pittsburgh'
AND birth_state = 'PA'
ORDER BY debut DESC, first_name ASC, last_name ASC;

"""

pd.read_sql(query,conn)

    first_name  last_name       debut
0        Mason     Miller  2023-04-19
1         Alex  Kirilloff  2021-04-14
2        David     Bednar  2019-09-01
3          Ian       Happ  2017-05-13
4        Kevan      Smith  2016-09-01
..         ...        ...         ...
129       Jake    Seymour  1882-09-23
130     Chappy       Lane  1882-05-16
131         Al      Pratt  1871-05-04
132      Denny   McKnight        None
133       Stan    Robison        None

[134 rows x 3 columns]

### **DATE FILTERING**

Players who debuted from the year 2000 onwards

In [13]:
query = """ 

SELECT ROUND(AVG(height), 2) AS 'Average height',
       ROUND(AVG(weight), 2) AS 'Average weight'
FROM players
WHERE debut >= '2000%';

"""

pd.read_sql(query,conn)

   Average height  Average weight
0           73.66          208.58

Players whose last game was in 2022

In [14]:
query = """ 

SELECT first_name, last_name
FROM players
WHERE final_game LIKE '2022%'
ORDER BY first_name ASC, last_name ASC;

"""

pd.read_sql(query,conn)

    first_name last_name
0        A. J.     Alexy
1        A. J.    Ladwig
2        Aaron     Ashby
3        Aaron    Brooks
4        Aaron  Fletcher
..         ...       ...
511       Zach     Logue
512       Zach      Reks
513       Zach  Thompson
514       Zack   Britton
515       Zack   Collins

[516 rows x 2 columns]

### **AGGREGATIONS**

Players who bat and throw with different hands

**Note:**

**bats != throws** would also include cases where one value is NULL

The correct approach is to explicitly define valid combinations: (L,R) and (R,L)

In [15]:
query = """ 

SELECT COUNT(id) AS "players opposite hand"
FROM players
WHERE (bats = 'L' AND throws = 'R')
   OR (bats = 'R' AND throws = 'L');

"""

pd.read_sql(query,conn)

   players opposite hand
0                   2925

### **ADVANCED ANALYSIS**

Players taller than the average

In [17]:
query = """ 

SELECT birth_country, first_name, last_name, height
FROM players
WHERE height > (
       SELECT AVG(height)
       FROM players
       )
ORDER BY height DESC, first_name ASC, last_name ASC
LIMIT 10;

"""

pd.read_sql(query,conn)

  birth_country first_name last_name  height
0           USA        Jon     Rauch      83
1           USA       Sean    Hjelle      83
2           USA      Aaron   Slegers      82
3           USA     Andrew  Brackman      82
4           USA       Andy     Sisco      82
5           USA      Chris     Young      82
6           USA       Eric   Hillman      82
7           USA      Randy   Johnson      82
8           USA       Adam  McCreery      81
9           USA       Alex     Meyer      81