# **Bed and Breakfast**

## **Context**

A Bed and Breakfast (BnB) is a type of short-term accommodation, similar to a hotel. With the rise of Airbnb, many people can now rent out their properties to tourists.

In this project, we analyze data from Boston using the bnb.db database to understand how Airbnb has influenced the city’s tourism.

## **Database Schema**

The database consists of three main entities:

**Listing:** represents each property available on Airbnb

**Review:** contains user reviews for each listing

**Availability:** stores information about when a listing is available

A Listing can have multiple Reviews and multiple Availability records over time

## **Tables Description**

### **listings**

The `listings` table contains the following columns:

- **id**: unique identifier of the listing  

- **property_type**: type of the listing (e.g., "Entire rental unit", "Private room in rental unit")  

- **host_name**: Airbnb username of the host  

- **accommodates**: maximum number of occupants  

- **bedrooms**: number of bedrooms  

- **description**: listing description on Airbnb  

---

### **reviews** 

The `reviews` table contains the following columns:

- **id**: unique identifier of the review  

- **listing_id**: ID of the listing that received the review  

- **date**: date the review was posted  

- **reviewer_name**: Airbnb username of the reviewer  

- **comments**: content of the review  

---

### **availabilities**

The `availabilities` table contains the following columns:

- **id**: unique identifier of the availability record  

- **listing_id**: ID of the associated listing  

- **date**: date of availability  

- **available**: whether the listing is available (TRUE or FALSE)  

- **price**: price for staying on that date

In [1]:
import pandas as pd 
import sqlite3
conn = sqlite3.connect("bnb.db")

In [2]:
def show_table(name):
    query = f"SELECT*FROM {name} LIMIT 5;"
    return pd.read_sql(query,conn)

In [3]:
show_table("listings")

,id,property_type,host_name,accommodates,bedrooms,description
0,3781,Entire rental unit,Frank,2,1.0,Fully separate apartment in a two apartment bu...
1,5506,Entire guest suite,Terry,2,1.0,"Private guest room with private bath, You do n..."
2,6695,Entire condo,Terry,4,NaN,"Comfortable, Fully Equipped private apartment..."
3,8789,Entire rental unit,Anne,2,1.0,This unit is for sale. There will need to be o...
4,10813,Entire rental unit,Michelle,2,NaN,Stunning Back Bay furnished studio apartment. ...

In [4]:
show_table("reviews")

,id,listing_id,date,reviewer_name,comments
0,1021,5506,2009-03-21,Jenny,Terry's Hotel Alterntv in Boston was a perfect...
1,1953,5506,2009-05-01,Clint,Warm and accommodating host. Beautiful and wel...
2,6826,6695,2009-08-06,Jaelen,Terry's apartment is beautifully decorated and...
3,8063,6695,2009-08-23,Patrick,We stayed in the private home / condo. A nice ...
4,10089,5506,2009-09-14,Nicolas,We stay 3 nights at the Hotel Alternative and ...

In [5]:
show_table("availabilities")

   id  listing_id        date available  price
0   1        3781  2023-06-22     FALSE    120
1   2        3781  2023-06-23     FALSE    120
2   3        3781  2023-06-24     FALSE    120
3   4        3781  2023-06-25     FALSE    120
4   5        3781  2023-06-26     FALSE    120


## **Creating Views for Analysis**

To better understand the data, we will create **SQL views**. 

By using views, we can extract focused subsets of the data, allowing us to isolate specific aspects of interest while filtering out irrelevant information. This makes it easier to work with targeted data, analyze patterns, and generate more precise insights.


### **View: available**

Dates that are available at all listings. The view contains the following columns:

**id**, which is the id of the listing 

**property_type**, from the listings table.

**host_name**, from the listings table.

**date**, from the availabilities table

In [15]:
query = """ 

DROP VIEW IF EXISTS "available";

CREATE VIEW "available" AS
SELECT "listing_id" AS "id", "property_type","host_name","date"
FROM "listings" JOIN "availabilities" ON
"listings"."id" = "availabilities"."listing_id"
WHERE "availabilities"."available" = 'TRUE';

"""
conn.executescript(query)

In [16]:
show_table("available")

     id       property_type host_name        date
0  3781  Entire rental unit     Frank  2023-07-14
1  3781  Entire rental unit     Frank  2023-07-15
2  3781  Entire rental unit     Frank  2023-07-16
3  3781  Entire rental unit     Frank  2023-07-17
4  3781  Entire rental unit     Frank  2023-07-18

### **View: frequently_reviewed**

This view contains the 100 most frequently reviewed listings, sorted from most to least frequently reviewed. The view contains the following columns:

**id**, which is the id of the listing from the listings table.

**property_type**, from the listings table.

**host_name**, from the listings table.

**reviews**, which is the number of reviews the listing has received.

In [ ]:
query = """ 

DROP VIEW IF EXISTS "frequently_reviewed";

CREATE VIEW "frequently_reviewed" AS
SELECT "listings"."id", "property_type", "host_name",
COUNT("reviews") AS "reviews"
FROM "listings" JOIN "reviews" ON 
"listings"."id" = "reviews"."listing_id"
GROUP BY "listings"."id"
ORDER BY "reviews" DESC, "property_type" ASC, "host_name" ASC LIMIT 100;

"""

conn.executescript(query)

In [18]:
show_table("frequently_reviewed")

         id         property_type                        host_name  reviews
0   4090224           Entire home                          Tiffany      860
1  18290558  Private room in home                    Boris & Susan      786
2    815639          Entire condo                            Jason      773
3    916123          Entire condo                            Jason      767
4  18584891  Private room in home  Roger Michael &Quot;Corey&Quot;      733